---
title: "DT"
author: "Delenn Bauer"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## DT

### Load Libraries and Data

```{r}
library(caret)
library(C50) # for decision tree
source("addrow.R")

carinsurance_train_dt <- read.csv("carinsurance_train.csv")
carinsurance_test_dt <- read.csv("carinsurance_test.csv")

```

### Build Model

```{r, cache=TRUE}
dtmodel <- C5.0(as.factor(OUTCOME1) ~ ., data = carinsurance_train_dt)
```

```{r, cache=TRUE}
dt_pred <- predict(dtmodel, carinsurance_test_dt)
```

```{r, cache=TRUE}
dt_cm <- confusionMatrix(as.factor(dt_pred), as.factor(carinsurance_test_dt$OUTCOME1), positive = "1")
dt_cm

write.csv(dt_pred, "dt_pred.csv", row.names = FALSE)
```


```{r, cache=TRUE}
TN <- dt_cm$table[1,1]
FN <- dt_cm$table[1,2]
FP <- dt_cm$table[2,1]
TP <- dt_cm$table[2,2]

# Profit
dt_profit <- 5000*TP - 500*FP
dt_kappa <- dt_cm$overall["Kappa"]

# Normalize profits to 1000
dt_profit <- (dt_profit / nrow(carinsurance_test_dt))*1000
append_row(dt_kappa["Kappa"], dt_profit, "DT")

dt_profit
dt_kappa
```

## Prediction with Probability for roc curve
```{r, cache=TRUE}
dt_pred_prob <- predict(dtmodel, carinsurance_test_dt, type = "prob")
summary(dt_pred_prob)
write.csv(dt_pred_prob, "dt_pred_prob.csv", row.names = FALSE)
```
