---
title: "KNN"
author: "Delenn Bauer"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## KNN

### Load Libraries and Data
```{r}
library(caret)
library(class)

carinsurance_train_knn_x <- read.csv("carinsurance_train_knn.csv")
carinsurance_train_knn_y <- read.csv("carinsurance_train_knn_label.csv")

carinsurance_test_knn_x <- read.csv("carinsurance_test_knn.csv")
carinsurance_test_knn_y <- read.csv("carinsurance_test_knn_label.csv")

summary(carinsurance_train_knn_x)
summary(carinsurance_train_knn_y)

```
### Build Model and Predict
```{r, cache = TRUE}
knn_pred <- knn(train = carinsurance_train_knn_x, test = carinsurance_test_knn_x, 
                cl = carinsurance_train_knn_y$x, k = 57, prob = TRUE)

summary(attributes(knn_pred)$prob)
```

```{r, cache=TRUE}
knn_cm <- confusionMatrix(as.factor(knn_pred), as.factor(carinsurance_test_knn_y$x), positive = "1")

knn_cm

write.csv(attributes(knn_pred)$prob, "knn_pred.csv", row.names = FALSE)
```

```{r, cache=TRUE}
TN <- knn_cm$table[1,1]
FN <- knn_cm$table[1,2]
FP <- knn_cm$table[2,1]
TP <- knn_cm$table[2,2]

# Profit
knn_profit <- 5000*TP - 500*FP
knn_kappa <- knn_cm$overall["Kappa"]

knn_profit
knn_kappa
```