---
title: "RF"
author: "Delenn Bauer"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RF

### Load Data and Libraries

```{r}
library(randomForest)
library(caret)
source("addrow.R")

rf_train <- read.csv("carinsurance_train.csv")
rf_test <- read.csv("carinsurance_test.csv")

str(rf_train)
summary(rf_train)
```
### Build Model

```{r, cache=TRUE}
set.seed(12345)
rfModel <- randomForest(as.factor(OUTCOME1) ~ ., data = rf_train)

summary(rfModel)
```

```{r, cache=TRUE}
randomForest::varImpPlot(rfModel)
```


### Predict and Export Prediction
```{r, cache=TRUE}
rfPred <- predict(rfModel, rf_test)
summary(rfPred)
```

```{r, cache=TRUE}
rf_cm <- confusionMatrix(as.factor(rfPred), as.factor(rf_test$OUTCOME1), positive = "1")
rf_cm

write.csv(rfPred, "rf_pred.csv", row.names = FALSE)
```

```{r, cache=TRUE}
TN <- rf_cm$table[1,1]
FN <- rf_cm$table[1,2]
FP <- rf_cm$table[2,1]
TP <- rf_cm$table[2,2]

# Profit
rf_profit <- 5000*TP - 500*FP
rf_kappa <- rf_cm$overall["Kappa"]

# Normalize profits to 1000
rf_profit <- (rf_profit / nrow(rf_test))*1000
append_row(rf_kappa["Kappa"], rf_profit, "RF")

rf_profit
rf_kappa
```